INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");
INSERT INTO users (name, age) VALUES ("A", "10");

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "cars", 1000, 10/15/18, 10/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "cars", 1000, 10/15/18, 10/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "cars", 1000, 10/15/18, 10/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "cars", 1000, 10/15/18, 10/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "cars", 1000, 10/15/18, 10/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "cars", 1000, 10/15/18, 10/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "cars", 1000, 10/15/18, 10/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "cars", 1000, 10/15/18, 10/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "cars", 1000, 10/15/18, 10/15/19);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "cars", 1000, 10/15/18, 10/15/19);

INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, "C", "B");
